const Router=require('express').Router()
const businessRoutes=require('../controller/business/business.routes')
const  senderRoutes=require('../controller/company/company.routes')
const  debtRoutes=require('../controller/debt/debt.routes')
const  brokerRoutes=require('../controller/broker/broker.routes')
const  labourRoutes=require('../controller/labour/labour.routes')
const  loadRoutes=require('../controller/load/load.routes')
const  amountgivenRoutes=require('../controller/amountgiven/amountgiven.routes')
const  billingRoutes=require('../controller/billing/billing.routes')
Router.use(businessRoutes)
Router.use(senderRoutes)
Router.use(debtRoutes)
Router.use(brokerRoutes)
Router.use(labourRoutes)
Router.use(loadRoutes)
Router.use(amountgivenRoutes)
Router.use(billingRoutes)
module.exports=Router